### ISSUE TITLE
component:pages/detail 컴포넌트 쪼개기

### ISSUE THREAD

**Issue by whtnqls124578** [whtnqls124578/velog-clone-nextjs#27]
## 종류

ISSUE 종류를 선택하세요

- [x] component

## 내용

- 내용 명:  detail page의 컴포넌트 쪼개기 계획 작업입니다.
https://www.figma.com/file/mHY8D3B66B39phzfb0cyEf/Untitled?t=VneaEEnSHgF4cJkZ-0

## 체크리스트

- [x] pigma에서 component 쪼개기

**Comment by youdaehoon** [comment]
이름이 좀 아쉽습니다. 시멘틱태그에 대하여 정리해보고 2차도 도전해주시면 감사하겠음미다 @whtnqls124578
