### ISSUE TITLE
readme: 작업일정 설정(2월 10일~)

### ISSUE THREAD

**Issue by whtnqls124578** [whtnqls124578/velog-clone-nextjs#36]
## 종류

ISSUE 종류를 선택하세요

- [x] readme

## 내용

- 내용 명:  1차 범위 작업일정 설정(2월 10일~)입니다.

## 체크리스트

- [x] 1차 범위 작업일정 설정

**Comment by youdaehoon** [comment]
주말은 작업하지맙시다. 평일로 분배해주세요 @whtnqls124578
