### ISSUE TITLE
component:pages/write 컴포넌트 쪼개기

### ISSUE THREAD

**Issue by whtnqls124578** [whtnqls124578/velog-clone-nextjs#41]
## 종류

ISSUE 종류를 선택하세요

- [x] component

## 내용

- 내용 명:  detail page의 컴포넌트 나누기.
<img width="900" alt="스크린샷 2023-02-14 오후 9 15 08" src="https://user-images.githubusercontent.com/100771469/218736440-0cabd8ee-85cb-4429-83bf-f41d8644568e.png">
https://www.figma.com/file/mHY8D3B66B39phzfb0cyEf/Untitled?node-id=0%3A1&t=DCtLqCv0G4woLQlJ-0

## 체크리스트

- [x] detail page의 컴포넌트 나누기 및 이름 지정

**Comment by youdaehoon** [comment]
굿 @whtnqls124578
